### PR TITLE
Issue297 vdi core pytest

### PR DESCRIPTION
**Pull request by JSchiefelbein**
Merge VDI 6007 validation test cases into VDI core branch #297

### CODE REVIEW

**Comment by MichaMans** [comment]
@JSchiefelbein thanks for implementing all 12 Cases. Could you implement and run them in the test_data.py test? For now we could leave the cases not validated out of the test. but with that we should have a nice coverage for our vdi implementation from the beginning

**Comment by JSchiefelbein** [comment]
I am unsure, if understood you correct: All test cases are called from the pytest environment in test_data.py. However, I left them within the verification folder. Thus, users have the option to plot validation results (and use the pytest framework)

**Comment by MichaMans** [comment]
Hi, yes it would be nice if we run the py.test that the 12 validation cases (except the 4 not beeing within the validation borders) will be calculated and compared. So that we have 62 tests in our pytest called. I can't find the calls for the validation cases within the pytest_data.py

**Comment by JSchiefelbein** [comment]
pytest

**Comment by JSchiefelbein** [comment]
Like this?

**Comment by JSchiefelbein** [comment]
Seems to work fine on issue297_vdi_core_pytest

**Comment by MichaMans** [comment]
Can't reproduce this. We got 12 files changed, no work in pytest_data.py, how can i run this with py.test? Travis is also testing agains 50 cases. Thats weird 😄

**Comment by JSchiefelbein** [comment]
You are right...I cannot find the current version on github, too :-D

**Comment by MichaMans** [comment]
Haha ok. Then we have a hint now, it's no pushed already 😃

**Comment by JSchiefelbein** [comment]
Prob. need a coffee :-P

**Comment by MichaMans** [comment]
I added matplotlib to the requirements, hope travis will work now, commented the not running cases for a later implementation, maybe @mlauster could help with the validation on case 6, 9, 10, 11

**Comment by MichaMans** [comment]
Mhh, Travis is still failing for Python 2.7. We need to figure out why later. For now this is fine. So keep in mind:
vdi core working with Python >= 3.4 (except cases 6, 9, 10, 11)

I'll merge it tomorrow

**Comment by mlauster** [comment]
Give me some days to check the failing test cases, unfortunately 10 and 11 are tough cookies. But go ahead with merging, I will fix this afterwards.

**Comment by mlauster** [comment]
Hmm, weird that test cases 3,4 and 12 fail in 2.7 . Maybe something changed in the libs used to solve the models....

**Pull request merged**
