### PR TITLE
Issue463 bad god

### LINKED ISSUE #463: Reading CityGML file from Bad Godesberg throws error
## What is the problem?

- While loading an old, renowned CityGML file from Bad Godesberg, TEASER fails and throws errors that specific attributes are not set.

## Why do we want to solve it?

- To get this good old example working again

## How do we want to solve it?

- Adding the errors to the related exceptions

### PR DESCRIPTION
**Pull request by mlauster**
This closes #463 

Example works again

### CODE REVIEW

**Comment by PRemmen** [comment]
The file of BadGodesberg is rager large so testing might not be efficient. However would it be worthwhile integrating typical buildings of this files (that means building with missing attributes, buildings in different LoD and buildings as part of buildings) into our CityGML test file to test the input in a better and robust way?

Besides that, the changes look reasonable.

**Comment by mlauster** [comment]
You are right, @PRemmen, that would be valuable! Should I add it to this PR or start a new one? A new one might be better in terms of small PRs and clear issues.

**Comment by PRemmen** [comment]
Mhh.. for me it would be okay to integrate it into this PR any objections @MichaMans

**Comment by MichaMans** [comment]
No objections from my side :+1:

**Comment by mlauster** [comment]
@PRemmen, as this open now for a long time and I would first like to focus on other issues, could we merge that and open a new issue for unit tests?

**Comment by PRemmen** [comment]
I'd favour implementing a test first, this can be very simple, just one - four building(s) in CityGML format, just to check that the import is working.

**Comment by mlauster** [comment]
While scanning the branches, I found this open PR. Do we still plan to keep CityGML loader for the future or will this be deprecated?

**Comment by PRemmen** [comment]
In my opinion this can be deprecated in favour of new cool open-source tools ;-)

**Comment by mlauster** [comment]
@PRemmen, can you approve the changes? I will then merge...

**Comment by mlauster** [comment]
@PRemmen, just as addition: You already reviewed this and everything was fine except msissing tests. Since we agredd on skipping the tests due to soon deprecated functionalities, you simply need to change your review from "Changes requested" to "Approved".

**Comment by PRemmen** [comment]
I think we have a missunderstanding?! instead of merging i thought we do not include citygml in the next release, so it would not make any sense to merge it?

**Comment by mlauster** [comment]
This is then really a misunderstanding. :-) Sorry, my idea was to merge it to get the examples running and have one last stable version. I know at least one external person who is currently using the CityGML loader and is waiting for this fix. What I wanted to omit are the tests, since we plan to deprecate the functionality and it is not worth the effort to write the tests.
For me personally, it would help to keep the functionality for one more release that I can then reference to in my dissertation.
Any opinions on that? How to proceed now?

**Comment by PRemmen** [comment]
:see_no_evil: :innocent::laughing:

**Pull request merged**
