### PR TITLE
#491 added a test for the library versions

### PR DESCRIPTION
**Pull request by MichaMans**
after #489  is merged and the library versions are ajusted we can merge this and we get an automated test s for the library versions in the future.

Feedback welcome @mlauster @PRemmen

### CODE REVIEW

**Comment by MichaMans** [comment]
Ok, travis failing, we need to add a github token for the request. Might be a good solution. I'll create one tomorrow

**Comment by MichaMans** [comment]
Ok. Seems to work now. We need to adjust the libraries then and test again and see if travis fails. But all after #489 is merged

**Comment by MichaMans** [comment]
I test again the tags, releases on Github. Not the modelica code. Thats a good point! I can think about pulling every repo and test the version in the code. We could discuss this in #491 . For a first version this should work.
What i do:
- Install PyGithub (Python Github API)
- Get the latest releases of the modelica libraries (With a secret github token via travis_ci environmental variable)
- Compare them to the code in TEASER

**Comment by mlauster** [comment]
@MichaMans, what about merging this? :)

**Comment by MichaMans** [comment]
@mlauster i updated to the latest buildings library. Could you have a quick look and approve this?

**Comment by mlauster** [comment]
@MichaMans, go ahead and merge!

**Pull request merged**
