### PR TITLE
Issue590 variable naming

### PR DESCRIPTION
**Pull request by MichaMans**
Presolved #590, can merge if implemented in the AixLib

### CODE REVIEW

**Comment by MichaMans** [comment]
@katharinabr thanks for the renaming in the aixlib. can you test this branch here? if the renaming is done right? otherwise i can do that

**Comment by MichaMans** [comment]
@katharinabr @PRemmen this should work now. Needs to be merge for achieving a compatible teaser dev with aixlib dev again.

**Comment by katharinabr** [comment]
@MichaMans The renaming of the changed parameters seems to be correct. I haven't worked with TEASER yet.  So it would be great if you could do the test.

**Comment by PRemmen** [comment]
this should be tested with AixLib current development, right? @katharinabr

**Comment by katharinabr** [comment]
@PRemmen Yes, we already merged the changes into the development branch.

**Comment by MichaMans** [comment]
@PRemmen can this be merged?

**Comment by PRemmen** [comment]
Just updated Modelica version.

Single and MultiZone buildings simulate, so this can be merged

**Pull request merged**
