### PR TITLE
Issue136 aix lib version

### PR DESCRIPTION
**Pull request by mlauster**
This is to update the version number of AixLib within TEASER to V0.5.2, what is the current version of AixLib in `master`. Since this is some kind of bug and annoying for the user, I would merge it into TEASER `master` and increase the version to V0.5.4. This will then of course force a new release, what I will do after the merge.

### CODE REVIEW

**Comment by mlauster** [comment]
Ah, and we need to close #136 again afterwards.

**Comment by mlauster** [comment]
IBPSA is still up-to-date. Where do we need to adjust the AixLib in calculation.ibpsa? That would make no sense at all...

**Comment by MichaMans** [comment]
I thought we might adjust it here:
teaser/logic/buildingobjects/calculation/ibpsa in the init? Does the IBPSA TEASER modelsupport not need the parentlibrary version?

**Comment by mlauster** [comment]
No, that's fine, it only contains the version number of the ibpsa library, which is still up-to-date.

**Comment by MichaMans** [comment]
Ahh sorry, i figured out what my problem was / is. I was looking at the development branch. There we specifiy the Parent Library versions in the mentioned ibpsa class. So this here is all fine. #492 might be an enhancement nevertheless.

**Comment by mlauster** [comment]
Ah, I saw an instant ago as well! Then we should fix this at frist, merge it into `master`, merge `master` into `development`and then check all other libraries.

**Comment by MichaMans** [comment]
Yes. We should fix it in the master by merging this pr. then we see how we will handle the future version in the development

**Pull request merged**
