### PR TITLE
Issue29 pep8

### PR DESCRIPTION
**Pull request by mlauster**
Fixes a lot of PEP008 issues and a small bug in EST archetypes

### CODE REVIEW

**Comment by PRemmen** [comment]
unit test to not run! Failing unit tests are:

- test_type_bldg_institute8
- test_type_bldg_institute4
- test_type_bldg_institute
- test_type_bldg_office

**Comment by mlauster** [comment]
Hm, can you give more information about why they are not running? So far, the changes in the related files look fine.

**Comment by PRemmen** [comment]
e.g. for office : 
unbenannt

you can run the unit tests yourself:

Just go to your TEASER folder and type: py.test (e.g. D:\GIT\TEASER>py.test) pytest should be installed as this is a requirement for TEASER if not: pip install pytest

**Comment by mlauster** [comment]
Fixed!

**Comment by PRemmen** [comment]
unit tests run, this can be merged in development!

**Pull request merged**
