### PR TITLE
WIP Merge persons and machines changes 

### PR DESCRIPTION
**Pull request by nhuelsenbeck**
[Issue567](https://github.com/RWTH-EBC/TEASER/issues/567) was solved, but this pull request should be hold back until [issue690](https://github.com/RWTH-EBC/AixLib/issues/690) in AixLib has been solved.

### CODE REVIEW

**Comment by nhuelsenbeck** [comment]
@MartinRaetz Yes, I checked it. Both Skripts in AixLib --> Database --> ThermalZones were using the persons value. I changed it according to the new calculation method.

**Comment by MichaMans** [comment]
@nhuelsenbeck @MartinRaetz if this is directly connected to an AixLib issue we should link that and keep track of that for the merging actions etc

**Comment by MichaMans** [comment]
@DaJansenGit @MartinRaetz Checks are passing now. If all exports and models are working and simulating, you can merge this and the AixLib branch simultaneously.

**Comment by PRemmen** [comment]
@DaJansenGit @MartinRaetz  please have a look at my comment in #568

**Comment by DaJansenGit** [comment]
some more detailed information about differences can be found in #567

**Pull request merged**
