### PR TITLE
Issue466 tabula example

### PR DESCRIPTION
**Pull request by PRemmen**
This solves #466 and adds examples for TABULA. In addition it solves problems with retrofitting tabula buildings and extends the retrofit tests

### CODE REVIEW

**Comment by PRemmen** [comment]
I will add some tests to cover missing lines in project.py

**Comment by MichaMans** [comment]
@PRemmen should we add this test for now? And maybe implement further tests for increasing coverage? At the moment this should be fine for me

**Comment by MichaMans** [comment]
a slightly decreasing coverage will be fine. Should we merge this? @PRemmen

**Comment by PRemmen** [comment]
thanks for approving @MichaMans

**Pull request merged**
