### PR TITLE
Issue612 co2 model

### PR DESCRIPTION
**Pull request by MartinRaetz**
This solves: https://github.com/RWTH-EBC/TEASER/issues/612

### CODE REVIEW

**Comment by MartinRaetz** [comment]
I actually think the lines 72 - 77 in teaser/data/output/modelicatemplate/AixLib/AixLib_Multizone could be deleted completely. The thermal zone is automatically set in the modelica multizone models.

**Comment by MartinRaetz** [comment]
@katharinabr implemented a reduced number of thermal zones in the AixLib (https://github.com/RWTH-EBC/AixLib/pull/1052). The use of Co2-balance and Moisture-balance is now optional via: 
use_C_flow = true,
use_moisture_balance = true,

Should we think about abandoning the internalgainsmode = 3 and set all co2 and moisture balance directly?

**Comment by MartinRaetz** [comment]
There seems to be an issue with the Travis-ci. Even after 4 days and retriggering it is still pending.

Nevertheless, the Travis-ci should not be required anymore, since we have coveralls?

@DaJansenGit, I think it would be okay to perform a "force merge" if you approve my changes. Otherwise, let me know and I will try to get more information about Travis and Coveralls.

**Review by DaJansenGit — APPROVED** [review]
everything fine! :)

**Pull request merged**
