### PR TITLE
Release 036

### PR DESCRIPTION
**Pull request by PRemmen**
@MichaMans @mlauster could you check your changes again in this branch? :-) 

I will do some testing and then change also the version numbers

### CODE REVIEW

**Comment by MichaMans** [comment]
pytests are not running when outputdata is emtpy or does not exist. I'll take a look, but if you know whats going wrong here, let me know

**Comment by PRemmen** [comment]
not yet ready to merge!

**Comment by PRemmen** [comment]
Ready to merge, @MichaMans could you run unit tests in linux once again?

should solve: #260 #259 #255 #254 #214 #190 #181

**Comment by MichaMans** [comment]
pytests are running under ubuntu and python3.5.1, 2.7.11

**Comment by PRemmen** [comment]
also #252 and extended examples in this release. Unit test still runs. Let's give it a try @MichaMans

**Comment by MichaMans** [comment]
This should run properly and solves a few bugs.
i'll merge it

**Pull request merged**
